export const APP_CONFIG = Object.freeze({
  appName: 'MoXin Quiz',
  appVersion: '5.0.0-dev',
  releaseChannel: 'development',
  schemaVersion: '2.0',
  cloudSyncSchemaVersion: 1,
  dbName: 'moxin-quiz-v3',
  dbVersion: 4,
  legacyStoragePrefix: 'moxin.',
  features: Object.freeze({
    v5DataFoundation: true,
    cloudSync: true,
    syncUi: true,
  }),
  cloud: Object.freeze({
    provider: 'google-drive',
    minimumClientVersion: '5.0.0',
    googleClientId: '465928667951-721b0udej0814jjelmepk0h98c57cf2a.apps.googleusercontent.com',
    googleIdentityScriptUrl: 'https://accounts.google.com/gsi/client',
    googleDriveScope: 'https://www.googleapis.com/auth/drive.appdata',
    googleDriveApiBaseUrl: 'https://www.googleapis.com/drive/v3',
    googleDriveUploadBaseUrl: 'https://www.googleapis.com/upload/drive/v3',
    resumableThresholdBytes: 5 * 1024 * 1024,
  }),
  syncLimits: Object.freeze({
    idleDebounceMs: 5 * 1000,
    activePendingMaxMs: 30 * 1000,
    maxCommitMutations: 250,
    maxCommitJsonBytes: 1024 * 1024,
    checkpointEveryCommits: 100,
    checkpointMaxAgeMs: 7 * 24 * 60 * 60 * 1000,
  }),
  packageLimits: Object.freeze({
    maxZipBytes: 100 * 1024 * 1024,
    maxUncompressedBytes: 250 * 1024 * 1024,
    maxSingleFileBytes: 25 * 1024 * 1024,
    maxFiles: 5000,
    maxCompressionRatio: 100,
  }),
});
